baseURL = "https://sdopendata.netlify.app/"
languageCode = "en-us"
title = "City of San Diego Open Data Portal"
relativeURLS = true

[params]
	bootstrap = "5.0.2"
	excelLimit = 1048576
	rowNosCsv = "https://seshat.datasd.org/seaboard/distribution_row_nos.csv"
	dsViewsCsv = "https://seshat.datasd.org/seaboard/dataset_views_copy.csv"

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
	category = "categories"
	tag = "tags"
	department = "departments"

preserveTaxonomyNames = true

[outputs]
	home = ["HTML", "JSON"]
	section = ["HTML","JSON"]
